users = [
    {
    'mail':'some_mail@gmail.com',
    'password':'letmeinletmeinletmein',
    'first_name':'Anastasiia',
    'last_name':'Dyomshina',
    'fathers_name':'Mikolayvna',
    'birthdate':'13/04/1999',
    'tel':'+380843669436',
    'education':"Level-up - Front End course; IT-Step - Python course",
    'skills':'HTML/CSS, JS, Python, SQLite, SQLAlchemy, Flask',
    'experience':'None',
    'u_img':'cool.jpg'
    },
    {
    'mail':'another_mail@gmail.com',
    'password':'12345',
    'first_name':'John',
    'last_name':'Smith',
    'birthdate':'14/05/2001',
    'tel':'+380987654321',
    'education':"Some school or other",
    'skills':'Java, PHP, C#, C++',
    'experience':'Some',
    },
    {
    'mail':'cool_mail@gmail.com',
    'password':'69420',
    'first_name':'Hanako',
    'last_name':'Yamada',
    'birthdate':'12/03/1998',
    'tel':'+380123456789',
    'education':"good one",
    'skills':'malbolge, chicken, brainfuck, piet, JavaScript',
    'experience':'Lots',
    },
]